CMAKE_MINIMUM_REQUIRED(VERSION 3.22.1)
PROJECT(xpmover)

INCLUDE(CheckIncludeFile)

SET(CMAKE_BUILD_TYPE Debug)
SET(CMAKE_POSITION_INDEPENDENT_CODE TRUE)
#SET(CMAKE_FIND_DEBUG_MODE TRUE)
#SET(CMAKE_VERBOSE_MAKEFILE ON)
SET(BUILD_TESTS TRUE)

#FIND_PACKAGE(OpenGL REQUIRED)

SET(COMMON_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/psx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/threads_compat.c
)

# check if C11 compatibility wrappers are needed for threads.h and subsequently time.h
CHECK_INCLUDE_FILE(threads.h HAVE_C11_THREADS)
IF(NOT HAVE_C11_THREADS)
    ADD_DEFINITIONS(-DNEED_C11_THREADS_WRAPPER)
    #SET(LINK_C11_COMPAT_STATIC "${LIB_BUILD}/libmesa_c11.a")
ENDIF()

SET(XPMOVER_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/plugin.c
    ${COMMON_SOURCES}
)

SET(LIB_BUILD "${CMAKE_CURRENT_SOURCE_DIR}/lib/_build")

SET(XPSDK_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/lib/XPSDK")
SET(XPSDK_INCLUDE "${XPSDK_ROOT}/CHeaders" CACHE STRING PATH)

IF(LINUX)
    ADD_LIBRARY(xpmover SHARED ${XPMOVER_SOURCES})
ELSEIF(WIN32)
    ADD_LIBRARY(xpmover MODULE ${XPMOVER_SOURCES})
ELSEIF(APPLE)
    ADD_EXECUTABLE(xpmover ${XPMOVER_SOURCES})
ENDIF()

IF(LINUX)
    #ADD_DEFINITIONS(-DTARGET_UNIX)
    ADD_DEFINITIONS(-DTARGET_LINUX)
    TARGET_COMPILE_DEFINITIONS(xpmover PUBLIC -DAPL=0 -DIBM=0 -DLIN=1 -DBUILD_PLUGIN=1)
    
    ADD_LIBRARY(xplm INTERFACE)
    ADD_LIBRARY(xpwidgets INTERFACE)
    SET_PROPERTY(TARGET xpmover APPEND_STRING PROPERTY LINK_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -rdynamic -nodefaultlibs -undefined_warning -fPIC -fvisibility=hidden")
ELSEIF(WIN32)
    ADD_DEFINITIONS(-DTARGET_WINDOWS)
    TARGET_COMPILE_DEFINITIONS(xpmover PUBLIC -DAPL=0 -DIBM=1 -DLIN=0 -DBUILD_PLUGIN=1 -D_CRT_SECURE_NO_WARNINGS)
    
    SET(XPLANE_LIBRARY_PATH "${XPSDK_ROOT}/Libraries/Win/")
    
    SET(GENERIC_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
    FIND_LIBRARY(XPLM_LIBRARY XPLM_64 HINTS "${XPLANE_LIBRARY_PATH}")
    FIND_LIBRARY(XPWIDGETS_LIBRARY XPWidgets_64 HINTS "${XPLANE_LIBRARY_PATH}")
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${GENERIC_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
    
    ADD_LIBRARY(xplm SHARED IMPORTED GLOBAL)
    ADD_LIBRARY(xpwidgets SHARED IMPORTED GLOBAL)
    SET_PROPERTY(TARGET xplm PROPERTY IMPORTED_IMPLIB "${XPLM_LIBRARY}")
    SET_PROPERTY(TARGET xpwidgets PROPERTY IMPORTED_IMPLIB "${XPWIDGETS_LIBRARY}")
ELSEIF(APPLE)
    ADD_DEFINITIONS(-DTARGET_MACOS)
    TARGET_COMPILE_DEFINITIONS(xpmover PUBLIC -DAPL=1 -DIBM=0 -DLIN=0 -DBUILD_PLUGIN=1)

    SET(XPLANE_LIBRARY_PATH "${XPSDK_ROOT}/Libraries/Mac/")
    SET(GENERIC_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
    FIND_LIBRARY(XPLM_LIBRARY XPLM HINTS "${XPLANE_LIBRARY_PATH}")
    FIND_LIBRARY(XPWIDGETS_LIBRARY XPWidgets HINTS "${XPLANE_LIBRARY_PATH}")
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${GENERIC_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})

    ADD_LIBRARY(xplm STATIC IMPORTED GLOBAL)
    ADD_LIBRARY(xpwidgets STATIC IMPORTED GLOBAL)
    SET_PROPERTY(TARGET xplm PROPERTY IMPORTED_LOCATION "${XPLM_LIBRARY}")
    SET_PROPERTY(TARGET xpwidgets PROPERTY IMPORTED_LOCATION "${XPWIDGETS_LIBRARY}")
ELSE()
    MESSAGE(FATAL_ERROR "Platform not recognized, check conditions in CMakeLists!")
ENDIF()

SET_PROPERTY(TARGET xplm APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${XPSDK_INCLUDE}/XPLM" "${XPSDK_INCLUDE}/Wrappers")
SET_PROPERTY(TARGET xpwidgets APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${XPSDK_INCLUDE}/XPLM" "${XPSDK_INCLUDE}/Widgets" "${XPSDK_INCLUDE}/Wrappers")

TARGET_COMPILE_DEFINITIONS(xpmover PUBLIC -DXPLM200=1 -DXPLM210=1 -DXPLM300=1 -DXPLM301=1 -DXPLM302=1 -DXPLM303=1 -DHAVE_XPLM)
TARGET_INCLUDE_DIRECTORIES(xpmover PUBLIC "${XPSDK_INCLUDE}/XPLM" "${XPSDK_INCLUDE}/Widgets" "${XPSDK_INCLUDE}/Wrappers" "${LIB_BUILD}")
TARGET_LINK_LIBRARIES(xpmover PUBLIC ${XPLM_LIBRARY} ${XPWIDGETS_LIBRARY} m)

IF(LINUX)
    TARGET_LINK_LIBRARIES(xpmover PUBLIC c)
ELSEIF(APPLE)
    SET(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
    SET_PROPERTY(TARGET xpmover APPEND_STRING PROPERTY LINK_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fPIC -fvisibility=hidden -bundle")
ELSEIF(WIN32)
    SET(OS_LIBRARIES bcrypt iphlpapi ws2_32)
    TARGET_LINK_LIBRARIES(xpmover PUBLIC ${OS_LIBRARIES})
    TARGET_LINK_OPTIONS(xpmover PRIVATE -static-libstdc++ -static-libgcc) # TODO: this relicenses the binary to GPL, replace by more liberal libraries
ENDIF()

IF(NOT APPLE)
	TARGET_LINK_OPTIONS(xpmover PRIVATE -Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/export_symbols.map)
ENDIF()

IF("${XPLANE_TARGET}" EQUAL "12.04")
    TARGET_COMPILE_DEFINITIONS(xpmover PUBLIC -DXPLM400=1)
ENDIF()

SET_TARGET_PROPERTIES(xpmover PROPERTIES PREFIX "")
SET_TARGET_PROPERTIES(xpmover PROPERTIES OUTPUT_NAME "xpmover")
SET_TARGET_PROPERTIES(xpmover PROPERTIES SUFFIX ".xpl")

IF(BUILD_TESTS)
    ADD_EXECUTABLE(manualtest-psx-client ${CMAKE_CURRENT_SOURCE_DIR}/src/manualtest_psx_client.c ${COMMON_SOURCES})
    TARGET_INCLUDE_DIRECTORIES(manualtest-psx-client PUBLIC "${LIB_BUILD}")
    TARGET_LINK_LIBRARIES(manualtest-psx-client PUBLIC ${LINK_C11_COMPAT_STATIC} ${OS_LIBRARIES} m)

    ADD_EXECUTABLE(manualtest-psx-parse ${CMAKE_CURRENT_SOURCE_DIR}/src/manualtest_psx_parse.c ${COMMON_SOURCES})
    TARGET_INCLUDE_DIRECTORIES(manualtest-psx-parse PUBLIC "${LIB_BUILD}")
    TARGET_LINK_LIBRARIES(manualtest-psx-parse PUBLIC ${LINK_C11_COMPAT_STATIC} ${OS_LIBRARIES} m)
ENDIF()
