name: Build

on:
  workflow_dispatch:
    inputs:
      commit_ref:
        description: 'commit ref to build'
        required: true
      ci_ref:
        description: 'CI system reference'

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: inputs-echo
        shell: bash
        run: |
          echo '#### JOB PARAMETERS - START'
          echo 'commit_ref=${{ github.event.inputs.commit_ref }}'
          echo 'ci_ref=${{ github.event.inputs.ci_ref }}'
          echo '#### JOB PARAMETERS - END'
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_ref }}
      - name: fetch-libs
        run: ./fetch-libs.sh
      - name: build-libs
        run: ./build-libs.sh
      - name: build
        run: ./build.sh
